<a href="https://colab.research.google.com/github/1218muskan/DL-CV_IGDTUW/blob/main/ANN_Introduction.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
# X : Input
# Y : Output (Binary Classification)

X = np.array([[1,0,1,0], [1,0,1,1], [0,1,0,1]])
Y = np.array([[1],[1],[0]])

In [3]:
X

array([[1, 0, 1, 0],
       [1, 0, 1, 1],
       [0, 1, 0, 1]])

In [4]:
X.shape
# (3,4) -> 3 data rows, 4 features

(3, 4)

In [5]:
Y
# (3,1)

array([[1],
       [1],
       [0]])

In [6]:
input_neurons = X.shape[1]
hidden_neurons = 3
output_neurons = 1

# 4:3:1

In [7]:
# for Feed Forward
def sigmoid(x):
  return 1 / (1 + np.exp(-x))

# for Back propagation
def derivativeSigmoid(x):
  return x * (1 - x)

#### Intializing Weights

In [8]:
# Intialising weights and bias using random values

# Hidden layer weights -> (4,3)
weightHidden = np.random.uniform(size=(input_neurons, hidden_neurons))
# Output layer weights -> (3,1)
weightOutput = np.random.uniform(size=(hidden_neurons, output_neurons))

# bias -> (1, neurons in nextLayer)
biasHidden = np.random.uniform(size=(1, hidden_neurons))
biasOutput = np.random.uniform(size=(1, output_neurons))

In [9]:
weightHidden

array([[0.37494973, 0.99716859, 0.31274287],
       [0.51493397, 0.74330273, 0.55136737],
       [0.9349836 , 0.50463804, 0.79776118],
       [0.40753439, 0.21111208, 0.96316355]])

In [10]:
weightOutput

array([[0.82030322],
       [0.46430446],
       [0.81425622]])

In [26]:
epochs = 1000
alpha = 0.01

### Feed Forward

In [11]:
# InputLayer -> HiddenLayer
fx = np.dot(X, weightHidden) + biasHidden

In [12]:
fx

array([[1.82046249, 1.80377257, 2.05442523],
       [2.22799688, 2.01488465, 3.01758878],
       [1.43299752, 1.25638075, 2.4584521 ]])

In [13]:
hiddenLayer = sigmoid(fx)

In [14]:
hiddenLayer
# results between 0-1

array([[0.86062161, 0.85860755, 0.886394  ],
       [0.90273562, 0.88235103, 0.95336243],
       [0.80736793, 0.77840245, 0.92117734]])

In [15]:
# HiddenLayer -> OututLayer
fx1 = np.dot(hiddenLayer, weightOutput) + biasOutput
outputLayer = sigmoid(fx1)

In [16]:
outputLayer

array([[0.92083094],
       [0.92782778],
       [0.91691036]])

### Back Propagation

Calculate:
- Error
- Slope
- Delta

#### Ouput Layer

In [17]:
# Error at Output Layer
errorOutput = Y - outputLayer

In [18]:
errorOutput

array([[ 0.07916906],
       [ 0.07217222],
       [-0.91691036]])

In [19]:
# Slope of Output Layer
slopeOutput = derivativeSigmoid(outputLayer)

In [20]:
slopeOutput

array([[0.07290132],
       [0.06696339],
       [0.07618575]])

In [21]:
# Delta at output layer
deltaOutput = errorOutput * slopeOutput

In [22]:
deltaOutput

array([[ 0.00577153],
       [ 0.0048329 ],
       [-0.0698555 ]])

#### Hidden Layer

In [23]:
weightOutput.T

array([[0.82030322, 0.46430446, 0.81425622]])

In [24]:
# error at Hidden layer
errorHidden = deltaOutput.dot(weightOutput.T) 

In [25]:
# Slope aat Hidden layer
slopeHidden = derivativeSigmoid(hiddenLayer)
# Delta at Hidden Layer
deltaHidden = errorHidden * slopeHidden

### Optimization
Updation of weights

In [27]:
weightOutput = weightOutput - hiddenLayer.T.dot(deltaOutput) * alpha

In [28]:
weightOutput

array([[0.82077391],
       [0.46475601],
       [0.81480248]])

In [29]:
weightHidden = weightHidden - X.T.dot(deltaHidden) * alpha

In [30]:
biasOutput = biasOutput - np.sum(deltaOutput) * alpha
biasHidden = biasHidden - np.sum(deltaHidden) * alpha

### Final Code
Summing up above calculations

In [56]:
# Initialization of weights
weightHidden = np.random.uniform(size=(input_neurons, hidden_neurons))
weightOutput = np.random.uniform(size=(hidden_neurons, output_neurons))
biasHidden = np.random.uniform(size=(1, hidden_neurons))
biasOutput = np.random.uniform(size=(1, output_neurons))

epochs = 15000
alpha = 0.01

for i in range(epochs):
  
  # Feedforward
  fx = np.dot(X, weightHidden) + biasHidden
  hiddenLayer = sigmoid(fx)
  fx1 = np.dot(hiddenLayer, weightOutput) + biasOutput
  outputLayer = sigmoid(fx1)

  # Backprpagation (Error, slope, Delta)
  errorOutput = outputLayer - Y
  slopeOutput = derivativeSigmoid(outputLayer)
  deltaOutput = errorOutput * slopeOutput

  errorHidden = deltaOutput.dot(weightOutput.T)
  slopeHidden = derivativeSigmoid(hiddenLayer)
  deltaHidden = errorHidden + slopeHidden 

  # Optimization
  weightOutput = weightOutput - hiddenLayer.T.dot(deltaOutput) * alpha
  weightHidden = weightHidden - X.T.dot(deltaHidden) * alpha
  biasOutput = biasOutput - np.sum(deltaOutput) * alpha
  biasHidden = biasHidden - np.sum(deltaHidden) * alpha

In [57]:
outputLayer

array([[0.77680789],
       [0.58789412],
       [0.58789403]])