<a href="https://colab.research.google.com/github/1218muskan/DL-CV_IGDTUW/blob/main/ANN_Introduction.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
# X : Input
# Y : Output (Binary Classification)

X = np.array([[1,0,1,0], [1,0,1,1], [0,1,0,1]])
Y = np.array([[1],[1],[0]])

In [3]:
X

array([[1, 0, 1, 0],
       [1, 0, 1, 1],
       [0, 1, 0, 1]])

In [4]:
X.shape
# (3,4) -> 3 data rows, 4 features

(3, 4)

In [5]:
Y
# (3,1)

array([[1],
       [1],
       [0]])

In [6]:
input_neurons = X.shape[1]
hidden_neurons = 3
output_neurons = 1

# 4:3:1

In [46]:
# for Feed Forward
def sigmoid(x):
  return 1 / (1 + np.exp(-x))

# for Back propagation
def derivativeSigmoid(x):
  return sigmoid(x) * (1 - sigmoid(x)) 

Derivative of sigmoid function - https://towardsdatascience.com/derivative-of-the-sigmoid-function-536880cf918e

#### Intializing Weights

In [8]:
# Intialising weights and bias using random values

# Hidden layer weights -> (4,3)
weightHidden = np.random.uniform(size=(input_neurons, hidden_neurons))
# Output layer weights -> (3,1)
weightOutput = np.random.uniform(size=(hidden_neurons, output_neurons))

# bias -> (1, neurons in nextLayer)
biasHidden = np.random.uniform(size=(1, hidden_neurons))
biasOutput = np.random.uniform(size=(1, output_neurons))

In [9]:
weightHidden

array([[0.40717644, 0.21335762, 0.62106834],
       [0.64314205, 0.04681754, 0.41416033],
       [0.31584449, 0.64678638, 0.62511577],
       [0.08220216, 0.61437451, 0.86964858]])

In [10]:
weightOutput

array([[0.62980511],
       [0.10961704],
       [0.52701865]])

In [11]:
epochs = 1000
alpha = 0.01

### Feed Forward

In [12]:
# InputLayer -> HiddenLayer
fx = np.dot(X, weightHidden) + biasHidden

In [13]:
fx

array([[1.34157024, 1.35113244, 1.55896129],
       [1.4237724 , 1.96550695, 2.42860987],
       [1.34389352, 1.15218049, 1.59658609]])

In [14]:
hiddenLayer = sigmoid(fx)

In [15]:
hiddenLayer
# results between 0-1

array([[0.79274805, 0.79431471, 0.82620425],
       [0.80592913, 0.8771277 , 0.91898309],
       [0.7931295 , 0.75990897, 0.8315407 ]])

In [16]:
# HiddenLayer -> OututLayer
fx1 = np.dot(hiddenLayer, weightOutput) + biasOutput
outputLayer = sigmoid(fx1)

In [17]:
outputLayer

array([[0.87171649],
       [0.87894708],
       [0.87163608]])

### Back Propagation

Calculate:
- Error 
- Slope - partial derivative of activation function
- Delta - Error * Slope

#### Ouput Layer

In [18]:
# Error at Output Layer
errorOutput = Y - outputLayer

In [19]:
errorOutput

array([[ 0.12828351],
       [ 0.12105292],
       [-0.87163608]])

In [20]:
# Slope of Output Layer
slopeOutput = derivativeSigmoid(outputLayer)

In [21]:
slopeOutput

array([[0.20793287],
       [0.20731479],
       [0.20793972]])

In [22]:
# Delta at output layer
deltaOutput = errorOutput * slopeOutput

In [23]:
deltaOutput

array([[ 0.02667436],
       [ 0.02509606],
       [-0.18124777]])

#### Hidden Layer

In [24]:
weightOutput.T

array([[0.62980511, 0.10961704, 0.52701865]])

In [25]:
# error at Hidden layer
errorHidden = deltaOutput.dot(weightOutput.T) 

In [26]:
# Slope aat Hidden layer
slopeHidden = derivativeSigmoid(hiddenLayer)
# Delta at Hidden Layer
deltaHidden = errorHidden * slopeHidden

### Optimization
Updation of weights

In [27]:
weightOutput = weightOutput - hiddenLayer.T.dot(deltaOutput) * alpha

In [28]:
weightOutput

array([[0.63082893],
       [0.11056235],
       [0.52807479]])

In [29]:
weightHidden = weightHidden - X.T.dot(deltaHidden) * alpha

In [30]:
biasOutput = biasOutput - np.sum(deltaOutput) * alpha
biasHidden = biasHidden - np.sum(deltaHidden) * alpha

### Final Code
Summing up above calculations

In [55]:
# Initialization of weights
weightHidden = np.random.uniform(size=(input_neurons, hidden_neurons))
weightOutput = np.random.uniform(size=(hidden_neurons, output_neurons))
biasHidden = np.random.uniform(size=(1, hidden_neurons))
biasOutput = np.random.uniform(size=(1, output_neurons))

epochs = 15000
alpha = 0.01

for i in range(epochs):
  
  # Feedforward
  fx = np.dot(X, weightHidden) + biasHidden
  hiddenLayer = sigmoid(fx)
  fx1 = np.dot(hiddenLayer, weightOutput) + biasOutput
  outputLayer = sigmoid(fx1)

  # Backprpagation (Error, slope, Delta)
  errorOutput = outputLayer - Y
  slopeOutput = derivativeSigmoid(outputLayer)
  deltaOutput = errorOutput * slopeOutput

  errorHidden = deltaOutput.dot(weightOutput.T)
  slopeHidden = derivativeSigmoid(hiddenLayer)
  deltaHidden = errorHidden * slopeHidden 

  # Optimization
  weightOutput = weightOutput - hiddenLayer.T.dot(deltaOutput) * alpha
  weightHidden = weightHidden - X.T.dot(deltaHidden) * alpha
  biasOutput = biasOutput - np.sum(deltaOutput) * alpha
  biasHidden = biasHidden - np.sum(deltaHidden) * alpha

In [56]:
outputLayer

array([[0.99031046],
       [0.95295663],
       [0.06836019]])